# This file defines the content types on the website. See the documentation for
# details: https://docs.bolt.cm/contenttypes/intro

# The Homepage content type is a singleton: There can be only one record of this
# content type.

homepage:
    name: Homepage
    singular_name: Homepage
    fields:
        title:
            type: text
            class: large
            group: content
            label: Title
        small_title:
            type: text
        cta1:
            type: text
        cta2:
            type: text
        image:
            type: image
        introduction:
            type: redactor
        content:
            type: redactor
        contentlink:
            type: text
            label: Link
            placeholder: 'contentType/slug or https://example.org/'
            postfix: "Use this to add a link for this Homepage. This could either be an 'internal' link like <tt>page//about</tt>, if you use a contentType/slug combination. Otherwise use a proper URL, like `https://example.org`."
            fixture_format: '{url}'
        slug:
            type: slug
            uses: title
            group: Meta
        seo:
            type: seo
            group: "SEO Settings"
    viewless: false
    taxonomy: [ categories ]
    singleton: true
    icon_many: "fa:home"
    icon_one: "fa:home"

general:
    name: General 
    singular_name: General
    fields:
        header_background:
            type: image
        service_tagline:
            type: text
            group: Service Page 
        service_caption:
            type: text
        service_description:
            type: text  
        contact: 
            type: set 
            group: Contact
            fields:
                phone:
                    type: text
                    group: Contact
                email:
                    type: email
                address: 
                    type: text
        socials:
            type: set 
            group: Social Media 
            fields:
                facebook:
                    type: text
                twitter:
                    type: text
                linkedin: 
                    type: text
        # Core features
        features:
            type: collection 
            group: Features
            fields:
                feature: 
                    type: set
                    fields:
                        title:
                            type: text
                        content:
                            type: redactor
    viewless: true 
    singleton: true
    icon_many: "fa:bars"
    icon_one: "fa:bars" 

# sliders
sliders: 
    name: Sliders
    singular_name: Slider
    locales: ['fr', 'en']
    viewless: true
    order: createdAt
    fields:
        title:
            type: text
            localize: true
        background:
            type: image
        sub_title:
            type: text
            localize: true
        link:
            type: text
        link_title:
            type: text
            localize: true
    icon_many: "fa:images"
    icon_one: "fa:image"
 
    
# Blog
blog:
    name: Blog
    singular_name: Blog
    locales: ['fr', 'en']
    fields:
        title:
            type: text
            localize: true
        text:
            type: article
            localize: true
        image:
            type: image
        slug:
            type: slug
            uses: title
        seo:
            type: seo
            group: "SEO Settings"
    taxonomy: [ categories, tags ]
    records_template: blog.twig
    record_template: blogitem.twig
    listing_records: 5
    icon_many: "fa:blog"
    icon_one: "fa:rss"
    
aurora:
    name: Aurora
    singular_name: Aurora
    locales: ['en', 'fr']
    fields:
        title:
            type: text
            localize: true
        caption: 
            type: text
            localize: true
        description:
            type: html
            localize: true
        feature_title:
            type: text
            localize: true
        feature_description:
            type: textarea
            localize: true
        feature_image:
            type: image
        template:
            type: templateselect
            filter: '/^[^_].*\.twig$/'
        slug:
            type: slug
            uses: title
        contentlink:
            type: text
            label: Link
            placeholder: 'contentType/slug or https://example.org/'
            postfix: "Use this to add a link for this Homepage. This could either be an 'internal' link like <tt>page//about</tt>, if you use a contentType/slug combination. Otherwise use a proper URL, like `https://example.org`."
            fixture_format: '{url}'
        seo:
            type: seo
            group: "SEO Settings"
    show_on_dashboard: true
    viewless: false
    default_status: published
    searchable: false
    icon_many: "fa:building"
    icon_one: "fa:building"

# The 'Blocks' ContentType is a so-called 'resource ContentType'. This means
# that it can be used to manage smaller pieces of content, like the 'about us'
# text, an 'our address' in the footer, or similar short blurbs of text.
# For more info, see: https://docs.bolt.cm/howto/resource-contenttype

services:
    name: Services
    singular_name: Service
    fields:
        title:
            type: text
        description:
            type: redactor
        headerBackground:
            type: image
        image:
            type: image
        innerTitle: 
            type: text
        innerDescription:
            type: html
        featuresList:
            type: redactor
        excerpt:
            type: text
        iconImage:
            type: text
        slug:
            type: slug
            uses: title
        seo:
           type: seo
           group: "SEO Settings"
    record_template: service.twig
    listing_template: services.twig
    order: createdAt
    icon_many: "fa:briefcase"
    icon_one: "fa:briefcase"

# Faq type
Faqs:
    name: Faqs
    singular_name: Faq
    locales: ['fr', 'en']
    listing_template: faqs.twig
    fields:
        title:
            type: text
            localize: true
        body:
            type: redactor
            localize: true

#Portfolio
portfolios:
    name: Portfolios
    singular_name: Porfolio
    fields:
        title:
            type: text
        image:
            type: image
            upload: portfolios
        client:
            type: text
        about:
            type: redactor
        website: 
            type: text
            required: true
        date:
            type: date
        category: 
            type: select
            values: [Non Lucratif, Entreprise, Université, E-commerce]
        features: 
            type: collection
            fields: 
                feature: 
                    type: text
        slug:
            type: slug
    taxonomy: portfolios
    icon_many: "fa:book"
    icon_icon: "fa:book"
    record_template: portfolio.twig

# Testimonials
testimonials:
    name: Testimonials
    singular_name: testimonial
    locales: ['fr', 'en']
    fields:
        client:
            type: text
            localize: true
        body:
            type: html
            localize: true
        image:
            type: image
    viewless: true
    
# Why Us partial
whyus:
    name: Whyus
    singular_name: Whyus
    locales: ['fr', 'en']
    fields: 
        small_title:
            type: text
            localize: true
        title: 
            type: text
            localize: true
        first_reason:
            type: text
            localize: true
        second_reason:
            type: text
            localize: true
        body: 
            type: html
            localize: true
        image_400x609:
            type: image
        image_400x349:
            type: image
        image_400x230:
            type: image
        link_to_about:
            type: text
        link_title:
            type: text
            localize: true
        image: 
            type: image
            group: "image settings"

    singleton: true
    viewless: true
    default_status: published
    sort: -id
    icon_many: "fa:cogs"
    icon_one: "fa:cog"
              
# Services sidebar call to action
cta:
    name: cta
    singular_name: cta
    locales: ['en', 'fr']
    viewless: true
    singleton: true
    fields:
        title:
            type: text
            localize: true
        body: 
            type: html
            localize: true
        tag_line:
            type: text
            localize: true
        tag_title:
            type: text
            localize: true
        cta_link:
            type: text
        cta_link_text: 
            type: text
            localize: true
        background_image:
            type: image
            
# We make
wemake:
    name: wemake
    singular_name: wemake
    locales: ['fr', 'en']
    singleton: true
    viewless: true
    fields:
        tagline:
            type: text
            localize: true
        title:
            type: text
            localize: true
        background: 
            type: image
        ceo_name:
            type: text
        ceo_image:
            type: image
            title: ceo image size(81x81)
            
# Stats
stats:
    name: Stats
    singular_name: Stat
    locales: ['en', 'fr']
    viewless: true
    sort: -createdAt
    fields:
        title:
            type: text
            localize: true
        stat_icon:
            type: text
        stat_number:
            type: text
        text:
            type: text
            localize: true
            
# Why us services
theylikeus:
    name: Theylikeus
    singular_name: Theylikeus
    locales: ['fr', 'en']
    viewless: true
    fields:
        title:
            type: text
            localize: true
        reason: 
            type: html
            localize: true
        
# Settings (general page)
settings:
    name: Settings
    singular_name: Setting
    singleton: true
    viewless: true
    fields:
        site_name:
            type: text
        footer_text:
            type: text
        services_background:
            type: image
        agency_background: 
            type: image
            group: home page settings
        our_benefits_image:
            type: image
            label: Our benefits image (370*301)
others:
    name: Others
    singular_name: Other
    locales: ['en', 'fr']
    viewless: true
    singleton: true
    title: Others
    fields:
        home:
            type: text 
            localize: true
        service_details:
            type: text 
            localize: true
        quick_links:
            type: text
            localize: true
        footer_background:
            type: image
        faq_title_small:
            type: text
            group: faqs settings
            localize: true
        faq_title:
            type: text
            localize: true
        faq_image:
            type: image
        faq_image_text:
            type: text
            localize: true
        testimonial_small_title:
            type: text
            group: testimonials settings
            localize: true
        testimonial_title:
            type: text
            localize: true
        testimonial_link:
            type: text
        testimonial_link_text:
            type: text
            localize: true
        blog_background:
            type: image
            group: "Blog Setting"
        home_tag:
            type: text
            localize: true
        home_title:
            type: text
            localize: true
        bottom_text:
            type: redactor
        bottom_text_cta:
            type: text
        service_tagline:
            type: text
            group: service homepage settings
            localize: true
        service_title:
            type: text
            localize: true
        service_background:
            type: image
  

# About
about:
    name: About
    singular_name: About
    singular_slug: apropos
    locales: ['fr', 'en']
    singleton: true  
    record_template: about.twig
    fields:
        title:
            type: text
            localize: true
        whyUs:
            type: text
            localize: true
        tag:
            type: text
            localize: true
        body:
            type: redactor
            localize: true
        image:
            type: image
        button_text:
            type: text
            localize: true
        button_link:
            type: text
        background:
            type: image
       
        ceo_name: 
            type: text 
            group: CEO
        ceo_image: 
            type: image


resource:
    name: resource
    singular_name: resource
    singleton: false
    locales: ['fr', 'en']
    fields:
        title:
            type: text
        tagline:
            type: text
        text:
            type: redactor
        button_text:
            type: text
        background:
            type: image
        slug:
            type: slug
            uses: [ title ]
        template:
            type: templateselect
        seo:
            type: seo
            group: "Seo settings"
   
# Ads
ads:
    name: Ads
    singular_name: Ad
    locales: ['fr', 'en']
    viewless: true
    fields:
        title:
            type: text
        description:
            type: redactor
        image:
            type: image
        link:
            type: text

contact:
    name: Contact
    singular_name: Contact
    singleton: true
    fields: 
        contact: 
            type: text
    icon_many: "fa:phone"
    icon_one: "fa:phone"

partners: 
    name: Partners
    singular_name: Partner
    viewless: true
    fields: 
        name: 
            type: text
        image: 
            type: image
        website: 
            type: text
    icon_many: "fa:handshake"
    icon_one: "fa:handshake"

counters: 
    name: Counters 
    singular_name: Counter
    viewless: true
    fields: 
        counter_icon: 
            type: text 
        count:
            type: number 
        name: 
            type: text 

our_benefits: 
    name: Our Benefits 
    singular_name: Our Benefit 
    viewless: true
    fields: 
        title: 
            type: text
        description: 
            type: redactor
