# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/menus

main-en:
  - label: Home
    title: This is the <b>first<b> menu item.
    link: homepage
    class: homepage
  - label: Services
    link: services
  - label: Blog
    link: blog
  - link: about
    label: About Us
    submenu:
        - label: FAQs
          link: faqs
  - label: Contact
    link: contact
  - label: Hébergement Web
    link: https://hosting.aurora.cm

main-fr:
  - label: Home
    title: This is the <b>first<b> menu item.
    link: homepage
    class: homepage
  - label: Services
    link:  services
    submenu:
        - label: Services
          link: 
            contenttype: services 

  - label: Contact
    link: contact
  - label: A Propos
    link: aurora/apropos
    class: apropos
  - label: Hébergement Web
    link: https://hebergement.aurora.cm
    class: bolt-site
    title: Meilleur hébergement web au Cameroun

footer-en:
    - label: Home
      link: /
    - label: Blog
      link: blog
    - label: Contact
      link: contact

footer-fr:
    - label: Home
      link: /
    - label: Blog
      link: blog
    - label: Contact
      link: contact
      
footer2-en:
    - label: Home
      link: /

footer2-fr:
    - label: Home
      link: /
