notification:
    enabled: true
    debug: false
    debug_address: njikam66@gmail.com # Email address used when debug mode is enabled
    debug_smtp: true
    subject: Your message was submitted
    subject_prefix: '[Boltforms]'
    replyto_name: '{NAME}'                 # Email addresses and names can be either the
    replyto_email: '{EMAIL}'                 # name of a field below or valid text.
    to_name: 'AURORA DIGITAL AGENCY'
    to_email: 'contact@aurora.cm'
    from_name: 'AURORA DIGITAL AGENCY'
    from_email: 'mailer@aurora.cm'
feedback:
    success: Message submission successful
    error: There are errors in the form, please fix before trying to resubmit

fields:
    name:
        type: text
        options:
            required: true
            attr:
                placeholder: Your name...
            constraints: [ NotBlank, { Length: { 'min': 3, 'max': 128 } } ]
    email:
        type: email
        options:
            required: true
            attr:
                placeholder: Your Email
                label: none
            constraints: [ NotBlank, Email ]
 
    subject:
        type: text
        options:
            required: true
            attr:
                placeholder: Subject
    message:
        type: textarea
        options:
            required: true
            label: Your message
            attr:
                placeholder: Your message...
                class: myclass
    my_recaptcha_v3_field:
            type: captcha
            options:
                captcha_type: recaptcha_v3
    submit:
        type: submit
        options:
            label: Submit my message »
            attr:
                class: thm-btn comment-form__btn
